# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

# When the user clicks on the button, open the modal 
@showAddEventForm = ->
  document.getElementById('add_event_form_div').style.display = 'block'
  return

# When the user clicks on <span> (x), close the modal
@hideAddEventForm = ->
  document.getElementById('add_event_form_div').style.display = 'none'
  return
  
 @showCreateGroupForm = ->
  document.getElementById('create_group_div').style.display = 'block'
  return

# When the user clicks on <span> (x), close the modal
@hideCreateGroupForm = ->
  document.getElementById('create_group_div').style.display = 'none'
  return
  
@showAddMemberGroupForm = ->
  document.getElementById('add_member_form_div').style.display = 'block'
  return

@hideAddMemberGroupForm = ->
  document.getElementById('add_member_form_div').style.display = 'none'
  return
  
@editEvent = (id) ->
  $('#edit_event_form_div').load("/edit_event/"+id);
  document.getElementById('edit_event_form_div_div').style.display = 'block'
  return

@hideEditEventForm = ->
  document.getElementById('edit_event_form_div_div').style.display = 'none'
  return

@showDeleteGroupConfirmationForm = ->
  document.getElementById('delete_group_confirmation_div').style.display = 'block'
  return

@hideDeleteGroupConfirmationForm = ->
  document.getElementById('delete_group_confirmation_div').style.display = 'none'
  return
# ---
# generated by js2coffee 2.2.0